//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17626
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TempCompiledTemplates
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Dynamic;
    using System.Linq;


    public class NewTaskEmailCommand : EmailModule.EmailTemplate
    {

#line hidden

        public NewTaskEmailCommand()
        {
        }

        public override void Execute()
        {

#line 1 "NewTaskEmailCommand.cs"

            From = Model.From;
            To.Add(Model.To);
            Subject = "Welcome to Daedalus";


#line default
#line hidden
        }
    }
}
